"""Problem 2: Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""

first, second = 0, 1

fib = []

limit = 4000000
while first + second <= limit:
    # Classical Fibonacci solution
    third = first + second
    fib.append(third)
    first = second
    second = third

sum_of_even = 0

for _ in fib:
    if _ % 2 == 0:
        sum_of_even += _

print(sum_of_even)
